name: Deploy to Staging

on:
  workflow_run:
    workflows:
      - CI
    types:
      - completed
    branches:
      - main

  workflow_dispatch:

permissions:
  contents: read

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  deploy:
    if: ${{ github.event_name == 'workflow_dispatch' || github.event.workflow_run.conclusion == 'success' }}
    name: Deploy Sigma rules to staging
    runs-on: ubuntu-latest
    environment:
      name: staging
    steps:
      - name: Checkout repository
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
        with:
          fetch-depth: 0
      
      - name: Download build artifact
        uses: actions/download-artifact@3e5f45b2cfb9172054b4087a40e8e0b5a5461e7c # v8.0.1
        with:
          name: converted-rules

      - name: Deploy to Staging
        run: |
          unzip converted-rules.zip
          echo "Deploying converted-rules to staging..."
          # Add deployment here
