name: Validate Sigma rules schema

on: [push, pull_request, merge_group, workflow_dispatch]

jobs:
  sigma-rules-validator:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v7

      - name: Set up Python
        uses: actions/setup-python@v6
        with:
          python-version: '3.11'

      - name: Validate Sigma rules
        uses: SigmaHQ/sigma-rules-validator@v1
        with:
          paths: |-
            ./rules
          schemaURL: https://raw.githubusercontent.com/SigmaHQ/sigma-specification/refs/heads/main/json-schema/sigma-detection-rule-schema.json
      
      - name: Install Sigma CLI and Plugins
        run: |
          pip install sigma-cli
          sigma plugin install kusto

      - name: Validate Rule Logic (sigma check)
        run: |
          sigma check ./rules

      - name: Test SIEM Translation (Smoke Test)
        run: |
          sigma convert -t kusto -p sentinel_asim -s ./rules/
